language: python
python: 3.6

install:
- pip install -r requirements.txt
- vagrant/travis prepare

script:
- vagrant/travis run

after_script:
- vagrant/travis cleanup

env:
  global:
  - DO_REGION=fra1
  - secure: Jzmhm3t3/3xHw3HN/einYLNJzSiobnlaaLU4xnIoFDRYD8uVyrFI3lIHzG8CB8xvdNhnAxt8YujmO6W+T4jHgXNDnAVvRFSEQXIfVTxqgZ37X1+Z8hrQ/TLJKngDZhURPbFvLQxZRIFd44RtBE6JmEcIMiK5bVOXH90nR+qW+fzHPoeXAh69oIm2FDammJSNm8hOY8vTLEUhJ/giLa+vZZ8DjEELpLwBLUzeTobOf1gnRLNP376aSEuy9G4MWKD8ZcK5HhMdfEVnipmFqgDMd+rh6UnmCQjpkR9DaRYxl7WiqY/a4eWTTcY6KfYr4ghq/EYbjEPlv5GsW4u78Ldg1w3VBQN4i8M0HBzFvej51+2i8KZq6YeGnpQ5X+rTwr+WCgiQIEgYy8FMYyMEDVcTpvczsjVE4f5Hyu+hIyGm5Bqsg9HvlBVZt3HW7OaL0lHaR2UM3AyRpOph7JT9CcVXXf41IMovp08IgAg9XWwPPjZ5ECQn1asslV4lrSvKo6IUYT1muKlpxJwE+uu+jURZsvCWV0aQUoeqD3VizKoNB2jvAv+nny5vz+ybPe/i0AXdATLAwUT6Fsljx2bak3+pV/vviE/SEHTqFYC8tEH4fV7UWWfGAESPp2FclyTQ4KdEhctmjjehfFgwOrqxMPJm1dGfGwPeQ8U1+kd+pmLZ7pU=

notifications:
  slack:
    secure: P8IAZZXZ7QWAOw9d7MpaE6o1X2vK9iQbNgBK6QgsqzCCE+GUkS6uaEAg8LGpsfbpBxuFYgSz5DdiwcN81/YhPIPsNjM2Ln/gV5QXCcqEuTlpzfisgZO/Dp3UDvHFB3Wcwszw8f0scfbxmn6czX8qy5rrliY42la8U2PlNq9iYWnGsfA/7+mRY84AKJfCQ1oGabip6S+w6MUYFsAzXELQl8pGFTfEMIfYULbKoXaqklORSx8nNVpcZ+Z6ZeQGczfODGkTkGsaYzYNQEua+shEwGick8Yf9UDJMQ28hHo7Mp3CKpLa38bIQ1Vl3pykVEKXYI/yDDK1qvtfU5ysa0taA1Vu/qJ00j0XRfzZRygjBEQRl53PBZ42mbDySbTKRCsI66iRtCBR2ZujYKKT36VsceI8I7tGsz0YelcG3UgGHDqszn8TSe+JKEdsTM1pW18qtU9GzW1dOO91ujKJeTfZdMPCcmzO7dpcF96q6smzDypOkTRtiAFAWtw9L6LwHd/yCyPGAQXe+KCP/evm4FCWtzBJpkX7RySRFuEDIFQHbhw2Rag+B+/k0+EMNYrYgzewOqU0v8sLcmX412t7C1t776+IA6lL7fSaVs7cs65HbJKUvZMfSs42Fsrw8OH7E4kkJ+JuQtwoWHs5NvkDhKoKATwuiwxbt5psV8LSn0Wu2BQ=
